# This is a config for E2B sandbox template.
# You can use template ID (z8ehoiwthkqsavztw2rx) or template name (vibe-nextjs-v1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-v1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-v1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-v1')

team_id = "8727b296-c3a4-4149-88ce-5221ab56be28"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-v1"
template_id = "z8ehoiwthkqsavztw2rx"
